trigger:
 branches:
  include:
     - master

pool:
 name: default

stages:
    - stage: Build
      displayName: 'Build app'
      jobs:
          - job: Buildapp
            displayName: 'BuildApp'
            

